### ISSUE TITLE
marmot-db API

### ISSUE THREAD

**Issue by NickNaso** [NickNaso/marmot-db#10]
Please take a look at this projects:

https://github.com/Level/rocksdb

https://github.com/Level/leveldown

Propose some ideas for the **marmot-db** API. The main usage of the marmot db is as cache system, but differently to other db I want handle the data type that it store. In other system for what I can understand you can only save string or buffer that essentially is an encoded string. 
My intention is to use:
- Number
- String
- Date
- Boolean
- Buffer

What do you think about that?

**Comment by grosa1** [comment]
Good idea. It's a simply and fast solution like mongo but with more control on data flow, right? I image it as a 2 level db. Saving in cache(temporary stored data) and saving directly in db. Otherwise a part of temporary data would be saved automatically(specified by the dev) after a while in the permanent storage.

**Comment by NickNaso** [comment]
Thanks all to take part of this discussion. Today I decided to bind the api of FASTER DB against **marmot-db**
